name: Test Action
description: A test action

runs:
  using: composite
  steps:
    - run: echo "runner.os=${{ runner.os }}"
      shell: sh
    - run: echo "job=${{ toJSON(job) }}"
      shell: sh
    - run: echo "runner=${{ toJSON(runner) }}"
      shell: sh
    - run: echo "env=${{ toJSON(env) }}"
      shell: sh
    - run: echo "strategy=${{ toJSON(strategy) }}"
      shell: sh
    - run: echo "needs=${{ toJSON(needs) }}"
      shell: sh
    - run: echo "matrix=${{ toJSON(matrix) }}"
      shell: sh
