[package]
name = "rust-pipelines"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dagger-sdk = "0.17"
eyre = "0.6"
octocrab = "0.43"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
