name: Some PR check

on:
  pull_request:
    branches: [main]


jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Something
        run: |
          echo echo echo echo echo εχο
