on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/runner-images/issues/10977#issuecomment-2810713336
      - run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
      - run: sudo apt-get update
      - run: sudo apt-get install -y qemu-system-x86 qemu-utils qemu-kvm
      - run: gpg --import --keyid-format LONG keys/Flatcar_Image_Signing_Key.asc
      - run: ./scripts/acquire.sh
      - run: ssh-keygen -C noreply@github.com -f "keys/id_ed25519" -N "" -t ed25519
      - run: sudo ./flatcar_production_qemu_uefi.sh -a keys/id_ed25519.pub -nographic &
      - run: ./scripts/wait_for_ssh.sh
        timeout-minutes: 1
      - run: ./scripts/ssh.sh hostname
      - run: |
          ./scripts/ssh.sh bash <<'EOF'
            docker run -it --rm python:3.12-slim python -c 'print("hello flatcar")'
          EOF
      - run: |
          ./scripts/ssh.sh bash <<'EOF'
            set -euo pipefail
            docker run -it --rm python:3.12-slim bash <<'EOT'
              set -euxo pipefail
              pip install pystack
              python3 -c 'import time; time.sleep(10)' &
              pystack remote $!
            EOT
          EOF
